global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true # Retain labels, as within PushGateway use
    static_configs:
    - targets: ['prometheus:9090', 'pushGateway:9091','org1peer-api.127-0-0-1.nip.io:8080', 'org2peer-api.127-0-0-1.nip.io:8080']

  - job_name: cadvisor
    scrape_interval: 1s
    static_configs:
    - targets: ['cadvisor:8888']
