name: Integration Tests

on:
  workflow_call:

jobs:
  fabric-integration-tests:
    name: Fabric Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache lerna
      id: cache-lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.node-version  }}-lerna-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.node-version }}-lerna-
    - name: Install project dependencies
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm install
    - name: Bootstrap lerna
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm run bootstrap
    - name: Fabric Integration Test
      run: .build/benchmark-integration-test-direct.sh
      env:
        BENCHMARK: fabric

  ethereum-integration-tests:
    name: Ethereum Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache lerna
      id: cache-lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.node-version  }}-lerna-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.node-version }}-lerna-
    - name: Install project dependencies
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm install
    - name: Bootstrap lerna
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm run bootstrap
    - name: Ethereum Integration Test
      run: .build/benchmark-integration-test-direct.sh
      env:
        BENCHMARK: ethereum

  besu-integration-tests:
    name: Besu Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache lerna
      id: cache-lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.node-version  }}-lerna-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.node-version }}-lerna-
    - name: Install project dependencies
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm install
    - name: Bootstrap lerna
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm run bootstrap
    - name: Besu Integration Test
      run: .build/benchmark-integration-test-direct.sh
      env:
        BENCHMARK: besu

  fisco-bcos-integration-tests:
    name: FISCO BCOS Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache lerna
      id: cache-lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.node-version  }}-lerna-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.node-version }}-lerna-
    - name: Install project dependencies
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm install
    - name: Bootstrap lerna
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm run bootstrap
    - name: FISCO BCOS Integration Test
      run: .build/benchmark-integration-test-direct.sh
      env:
        BENCHMARK: fisco-bcos

  generator-integration-tests:
    name: Generator Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache lerna
      id: cache-lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.node-version  }}-lerna-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.node-version }}-lerna-
    - name: Install project dependencies
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm install
    - name: Bootstrap lerna
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm run bootstrap
    - name: Generator Integration Test
      run: .build/benchmark-integration-test-direct.sh
      env:
        BENCHMARK: generator
