name: Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache lerna
      id: cache-lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.node-version  }}-lerna-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.node-version }}-lerna-
    - name: Check correct usage of Caliper package names
      run: ./scripts/check-package-names.sh
    - name: Install project dependencies
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm install
    - name: Bootstrap lerna
      if: steps.cache-lerna.outputs.cache-hit != 'true'
      run: npm run bootstrap
    - name: Check the version consistency of subpackages
      run: ./packages/caliper-publish/publish.js version check
    - name: Run unit tests
      run: npm test
